files = [
  "TerminessTTF NF.ttf",
  "LXGWWenKaiMono-Regular.ttf",
]

[style]
font_size = 26.0
padding_x = 12
padding_y = 8
background = "green"
color = "white"
border_color = "black"
border_width = 1
