services:
  inkframe:
    image: ghcr.io/zoranner/inkframe-server:latest
    container_name: inkframe
    restart: always
    env_file: ../.env
    ports:
      - 3521:3000
    volumes:
      - ../data:/app/data
networks:
  default:
    external: true
    name: inkframe
