services:
  inkframe-server:
    image: inkframe-server:latest
    container_name: inkframe-server
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ../.env
    volumes:
      - ./data:/app/data
