services:
  epaper-album-server:
    image: epaper-album-server:latest
    container_name: epaper-album-server
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ../.env
    volumes:
      - ./data:/app/data
